### ISSUE TITLE
Unrendered Unicode character U+23F5 on macOS

### ISSUE THREAD

**Issue by humphd** [microsoft/rushjs.io-website#106]
There's an improperly rendered Unicode character (at least on macOS) in the welcome docs at https://github.com/microsoft/rushjs.io-website/blob/21504a016c227c56c591c9dd61d50e1286da34b0/pages/intro/welcome.md?plain=1#L13

As seen in Chrome:

<img width="825" alt="Screen Shot 2021-10-09 at 11 22 22 AM" src="https://user-images.githubusercontent.com/427398/136664514-12c243ac-35ba-4ae4-8da5-e9b04f8f1a46.png">

And Firefox:

<img width="839" alt="Screen Shot 2021-10-09 at 11 22 31 AM" src="https://user-images.githubusercontent.com/427398/136664524-3c956c36-2e7a-4c95-80c0-91b645793881.png">

I guess it's https://www.compart.com/en/unicode/U+23F5, and probably a [macOS font issue](https://stackoverflow.com/questions/47059852/black-medium-right-pointing-triangle-symbol-not-working-on-mac).

**Comment by humphd** [comment]
Also found in:

- https://github.com/microsoft/rushjs.io-website/blob/master/pages/developer/everyday_commands.md?plain=1#L55
- https://github.com/microsoft/rushjs.io-website/blob/master/pages/advanced/installation_variants.md?plain=1#L141

**Comment by octogonz** [comment]
@humphd Thanks for reporting this!  We actually encountered this same problem before on the `tsdoc.org` website and the decision was to use 👉. I've applied that fix in https://github.com/microsoft/rushstack-websites/pull/88
