### ISSUE TITLE
Better linking of rushjs and rushstackjs websites

### ISSUE THREAD

**Issue by elliot-nelson** [microsoft/rushjs.io-website#108]
A user on Zulipchat said it was confusing to navigate rushjs and rushstackjs, since both look similar and have similiar (but usually non-overlapping) content, and they don't refer to each other.  (I agree, as a not-so-new user!)

We can keep them on separate domains, but having a global / overarching header template that brings the sites together would help new users navigate the project documentation.

**Comment by octogonz** [comment]
Done -- we solved this with the new suite nav.
