### ISSUE TITLE
Config page for '.pnpmfile.cjs' is showing a 404 page

### ISSUE THREAD

**Issue by cyrdam** [microsoft/rushjs.io-website#111]
The page for [.pnpmfile.cjs](https://rushjs.io/pages/configs/pnpmfile_cjs/) is not available (404 page).

The markdown file for that is here: [.pnpmfile_cjs.md](https://github.com/microsoft/rushjs.io-website/blob/master/pages/configs/.pnpmfile_cjs.md)

The file name might be the issue: begins with a dot.

**Comment by KebapBoy** [comment]
Probably related to #102.
I also didn't found the file at [_pnpmfile_cjs](https://rushjs.io/pages/configs/_pnpmfile_cjs/).

**Comment by KebapBoy** [comment]
I created a PR #118 that should fix the missing page and the link in the navigation.

**Comment by octogonz** [comment]
Thanks for spotting this!  Much appreciated!

The website has moved to a new Docusaurus repo, so I've started a separate PR over there to fix the problem: https://github.com/microsoft/rushstack-websites/pull/82
