### ISSUE TITLE
[Suggestion] Mark this repo deprecated.

### ISSUE THREAD

**Issue by bvanjoi** [microsoft/rushjs.io-website#124]
I had noticed that [rush](https://rushjs.io/) and [rushstack](https://rushstack.io/) had beed removed to https://github.com/microsoft/rushstack-websites, so I suggested mark [rushjs-website](https://github.com/microsoft/rushjs.io-website) and [rushstack-website](https://github.com/microsoft/rushstack.io-website) deprecated.

**Comment by octogonz** [comment]
This is now completed.
