### ISSUE TITLE
Documentation for `allowedProjectTags`

### ISSUE THREAD

**Issue by 7thias** [microsoft/rushjs.io-website#128]
Search on the website and on google returns zero hits for `allowedProjectTags`.

In the default rush config file, it has a comment about the property:
```
  /**
    * This is an optional, but recommended, list of available tags that can be applied
    * to projects. If this property is not specified, any tag is allowed. This
    * list is useful in preventing typos when specifying tags for projects.
    */
  "allowedProjectTags": [ "apps", "Web", "tools" ],
``` 

but I'm not sure what it means to "specify tags for projects".

**Comment by 7thias** [comment]
Ok so if I would have just kept reading in the rush config file the "projects" section has `tags` for project entries.

Still, the concept of tags could be mentioned on the web site. The search on the website has no relevant results for "tags" and how they might be used e.g. in commands.

**Comment by octogonz** [comment]
@7thias Thank you for pointing this out!  Fixed in https://github.com/microsoft/rushstack-websites/pull/85
