### ISSUE TITLE
Document how to debug Rush

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushjs.io-website#30]
Explain to do something like:

`alias testrush="node ~/git/wbt/apps/rush-lib/lib/start.js"`

Explain how to use the VS Code debugger.

**Comment by KevinGrandon** [comment]
This would be useful, also including the content in this wiki in the website would help, so community members could make pull requests: https://github.com/Microsoft/web-build-tools/wiki/Contributing-to-this-repo

**Comment by poelstra** [comment]
Just had to debug it myself, so for those wondering, here are the steps I took:

This shows how to debug the `rush update` command:
```
# (Re-)build the version of rush you want to debug, e.g. 5.10.3
git clone https://github.com/microsoft/web-build-tools.git
cd web-build-tools
git checkout @microsoft/rush-lib_v5.10.3
rush install && rush build

# Run debug version of `rush update` in your project
cd /your_project
code .
node --inspect-brk ~/src/web-build-tools/apps/rush-lib/lib/start.js update

# Now, in VSCode
# - go to Debugger > Add Configuration > Pick "Node.JS: Attach to Process"
# - Start debugger (F5), choose the running rush-lib process
# - Place breakbpoints etc
# - Happy debugging
```

**Comment by octogonz** [comment]
I use this, which avoids the need for `node --inspect-brk`:

**apps/rush-lib/.vscode/launch.json**
```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "rush update",
      "program": "${workspaceFolder}/lib/start.js",
      "args": [ "update" ],
      "cwd": "(repo folder that you want to debug)"
    }
  ]
}
```

Then you can just press the "play" button in VS Code.

Hmm...  Maybe we should add this file to Git [as we did](https://github.com/microsoft/web-build-tools/blob/master/apps/api-extractor/.vscode/launch.json) for API Extractor.

**Comment by octogonz** [comment]
Fixed in https://github.com/microsoft/rushjs.io-website/commit/df5a62b02f7e935f6dcbcc010a0fcbf9014e57e7

**Comment by DavidRieman** [comment]
Where do we find this documentation?  Is it meant to be on https://rushstack.io/pages/contributing/get_started/ ?  Am I just not seeing it, or should this be perhaps reopened?
