### ISSUE TITLE
Talk about docker and CI and Rush

### ISSUE THREAD

**Issue by wbern** [microsoft/rushjs.io-website#35]
Since rush supports incremental builds out of the box, it would be nice to mention a supported use case of docker images in build pipelines.

My personal idea of how to do this would be that you build a docker image as part of your pipeline build, but only when you already have one that is relatively fresh built from the source code. Say you build the next time, instead of doing a new docker build, instead you run docker commit (update: bad, just push new image instead, see next post), effectively saving the changes you made to the image but without rebuilding the image from scratch.

Since docker commit increases image size by quite a bit, some threshold would need to be respected to run a new docker image build again at some point. If the threshold isn't reached, a midnight execution could potentially help to restore the docker image.

The above could also theoretically work for all branches currently worked on, not just master branch.

The only limitation of this currently is that rush build has incremental builds, but not custom commands. So some feature branches that may want source maps or something like that would need to be able to receive an extra parameter via rush build and not via say rush build-with-sourcemaps.

**Comment by wbern** [comment]
Right, so scrapping the idea behind docker commit, multi stage builds work much better. 

Work in progress dockerfile.

```Dockerfile
# eg. "scratch" when starting a new branch (default), or eg. "wbern/rush-example:master"
ARG CACHE_IMAGE="scratch"
# ARG CACHE_IMAGE="wbern/rush-example:master"
ARG SOURCE_BRANCH="master"

# To make the previously pushed build available as build cache, respecting branch name
FROM ${CACHE_IMAGE} AS cache

WORKDIR /usr/src/app

FROM node:10

# Reuse the global --build-arg
ARG CACHE_IMAGE
ARG SOURCE_BRANCH

# Create app directory
WORKDIR /usr/src/app

# Get cached artifacts
COPY --from=cache /usr/src/app /usr/src/app

# Set it to use latest code, ignoring what's in gitignore
RUN ls -l
# RUN git remote add origin https://github.com/wbern/rush-example.git
RUN echo ${CACHE_IMAGE}


RUN [ -d /usr/src/app/.git ] && echo "Found" || echo "Not found"

# If the cache image is from "scratch", do git init etc.
RUN [ -d /usr/src/app/.git ] && \
    # cache file structure with .git directory exists
    (git fetch && git reset --hard origin/${SOURCE_BRANCH}) || \
    # .git directory did not exist, start with a new git init
    (git init && git remote add origin https://github.com/wbern/rush-example.git)

RUN node ./common/scripts/install-run-rush.js install --bypass-policy

RUN node ./common/scripts/install-run-rush.js build

CMD /bin/bash
```

**Comment by wbern** [comment]
The above will preserve everything from node_modules to package-deps.json files in the build structure. Probably not ideal, but it's a start.

**Comment by octogonz** [comment]
Cool, thanks for writing this up!

**Comment by paynecodes** [comment]
@wbern I find myself consistently stumbling across solutions you are posting. It's been quite some time since this issue was created and updated. Do you have any further resources to point to regarding CI docker builds with rush?

**Comment by wbern** [comment]
@paynecodes ah this is an interesting issue you stumbled on indeed. 🙂

Rush now has some basic support for build caching, which is essentially what I wanted to accomplish here.

Docker _kinda_ works for caching everything, but it has some lead times since the docker image gets quite big in a large repo, and the copy operation, the image export, and the image publishing (if needed) all take up valuable seconds and minutes.

What is the specific issue you're trying to solve in this case?

Also I'm gonna close this issue because I believe there are better ways to achieve what I tried to achieve above. Feel free to keep posting though!

**Comment by paynecodes** [comment]
Ah, I see. I'm really just scouring the internet for help regarding rush and docker in a CI context.

**Comment by wbern** [comment]
@paynecodes it would be helpful to know what you're trying to solve! Maybe try the zulip chat?

**Comment by paynecodes** [comment]
@wbern You are correct. I'm not doing a good job at explaining what I'm looking for. Essentially, given that Rush is a monorepo tool, I am looking for wholistic guidance on how folks build and **deploy** their various applications. I have a few wants and desires for my needs, but generalized advice regarding the following is what I am seeking given the very specific nature of concrete deployment tooling etc (AWS CodePipeline, Jenkins, Travis, CirclieCI, Azure Pipelines, etc.).

- Monorepo oriented CI/CD guidance around topics such as changed project detection
- Best practices for production ready docker builds 

Here's the [zuilip chat](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/monorepo.20deploy.20beginner) that hasn't picked up much traction.
