### ISSUE TITLE
Discussion: Making 'common' folder configurable

### ISSUE THREAD

**Issue by fearthecowboy** [microsoft/rushjs.io-website#36]
I originally had projects with category folders, and several projects in them,  but I'm breaking the mega mono-repo up into smaller pieces, because the developers working on those components only need to focus on their little piece and are happy bringing in the shared components as packages from npm.

it's likely that only one or two people will ever need to have a mega-mono-repo of everything, and to handle that I was going to create a mono-repo that just brought in the other mono repos as submodules. (works great)

This was good, as it makes sense to move to using rush for everything, even when there is only a single project in a repo, because then the pattern is perfectly consistent (always `git clone` / `rush update` / `rush rebuild`)

I started setting up the mono-repos, and trying to keep the number of subfolders down, to keep the complexity low and to keep it from getting too deep.

But when I switched to putting subprojects off the root for the repos, the `common` folder gets between a couple of the names of the subprojects. (alphabetically)

### AProject 
```
.
     .scripts/ # per-project scripts (ie, ADO yaml files, etc)
     alphasub/
     common/
     gammasub/
     .gitattributes
     .gitignore
     license
     package.json # just has minimal metadata and scripts -- no packages
     readme.md 
     rush.json
```

### BProject
```
.
  .scripts/ # per-project scripts (ie, ADO yaml files, etc)
  betasub
  common/
  thetasub
  .gitattributes
  .gitignore
   license
   package.json # just has minimal metadata and scripts -- no packages
   readme.md 
   rush.json
```

It's a mild PITA that the common folder is fixed to `common` in that it gets inbetween the subprojects in the project.

I don't want to use category folders, because the mega-repo that pulls in the others as submodules ends up having a lot of depth that is just irritating.

worst case scenario:

```
  .scripts/
  common/
  projects/
    a-project/
       alphasub/
        <contents...>
      common/ 
      gammasub/
        <contents...>
      b-project/
        betasub/
          <contents...>
         common/ 
         thetasub/
          <contents...>
    project.json
    rush.json           
```

Ideally, the mega is fairly thin, and the `common` folder isn't in the way.

### MegaRepo Project
```
   .scripts/ # per-project scripts (ie, ADO yaml files, etc)
   .rush/ # better spot for common 
   a-project/  #submodule
      .rush/ # better common folder from a-project
      alphasub/
      gammasub/
   b-project/ #submodule
      .rush/  # better common folder from b-project
      betasub/
      thetasub/
    package.json
    rush.json 
```

the actual code at this point ends up four levels deep, and all those nested folders make for really nested `node_modules` folders too

so, I'm definitely eliminating the category folder so that it's not so nested.

The sad part is the developer sees `common` smack dab in the middle of things.

The other thing that making `commonFolder` configurable would do is that the mega-repo could potentially set it's common folder to `/a-project/.rush` and share the `common`  folder (where we keep `command-line.json` etc ).. (not a big feature, but hey..)

**Comment by octogonz** [comment]
Moved to https://github.com/microsoft/web-build-tools/issues/1511
