### ISSUE TITLE
`rush publish` docs refer to non-existent `--commit` flag

### ISSUE THREAD

**Issue by mpiroc** [microsoft/rushjs.io-website#47]
The documentation for [`rush publish`](https://rushjs.io/pages/commands/rush_publish/) states:

> ```
> Reads and processes package publishing change requests generated by "rush
> change". This will perform a read-only operation by default, printing
> operations executed to the console. To commit changes and publish packages,
> you must use the --commit flag and/or the --publish flag.
> ```

However, the `--commit` flag does not exist. It does not appear in `rush publish -h`, and if included results in the message `Unrecognized arguments: --commit.`

Example:

```
> rush change
...
> rush publish --pack --apply --include-all --release-folder ./release --version-policy my-version-policy
# Nothing is written to ./release

> rush publish --pack --apply --include-all --release-folder ./release --version-policy my-version-policy --commit
rush publish: error: Unrecognized arguments: --commit.
```

Environment:
```
> rush --version
Rush Multi-Project Build Tool 5.17.0 - https://rushjs.io
Node.js version is 10.16.3 (LTS)
```

**Comment by octogonz** [comment]
The commit flag does exist, but you need to specify an argument:
```
  -c COMMIT_ID, --commit COMMIT_ID
                        Used in conjunction with git tagging -- apply git
                        tags at the commit hash specified. If not provided,
                        the current HEAD will be tagged.
```
