### ISSUE TITLE
Provide a link to rushjs.io-website GitHub repo in rushjs.io and rushstack.io

### ISSUE THREAD

**Issue by sachinjoseph** [microsoft/rushjs.io-website#62]
This will help customers file documentation issues more easily.

**Comment by octogonz** [comment]
@ sachinjoseph what do you mean? Both websites have a "GitHub" link in their top nav:

- https://rushstack.io/
- https://rushjs.io/

**Comment by sachinjoseph** [comment]
Sorry, I should have been clearer. I was hoping if we could provide links to https://github.com/microsoft/rushjs.io-website and https://github.com/microsoft/rushstack.io-website. Currently, the GitHub sections in both sites don't have links to the website repos.

**Comment by psjishnu** [comment]
@sachinjoseph  Which will be the ideal place to provide links to https://github.com/microsoft/rushjs.io-website and https://github.com/microsoft/rushstack.io-website

**Comment by sachinjoseph** [comment]
Thanks Jishnu @psjishnu. Do you want to take this up? :-) 

This looks like the right place on rushjs.io: https://rushjs.io/pages/contributing/

I believe there is an equivalent page on rushstack.io.

**Comment by psjishnu** [comment]
@sachinjoseph  Are you telling that https://rushjs.io/pages/contributing/  should contain contents equivalent to the https://rushstack.io/pages/contributing/get_started/ ?

**Comment by sachinjoseph** [comment]
Well, you could. But as far as this specific issue is concerned, just a link to the docs repo on both these websites would suffice.

**Comment by sachinjoseph** [comment]
I recommend starting with a link PR if you want to work on this, and then open a new issue to discuss enhancing the content.

**Comment by psjishnu** [comment]
@sachinjoseph  

> Sorry, I should have been clearer. I was hoping if we could provide links to https://github.com/microsoft/rushjs.io-website and https://github.com/microsoft/rushstack.io-website. Currently, the GitHub sections in both sites don't have links to the website repos.

Sorry I was just planning to solve this issue . I just meant that is it enough to provide  links  to https://github.com/microsoft/rushjs.io-website and https://github.com/microsoft/rushstack.io-website to the corresponding  contribution page of website .

**Comment by sachinjoseph** [comment]
That should be enough for resolving this issue.

**Comment by psjishnu** [comment]
So there will be 2 links in both the contribution pages . For example in Runstack contribution page contains link to both https://github.com/microsoft/rushstack/ and https://github.com/microsoft/rushstack.io-website. Am I right ?

**Comment by sachinjoseph** [comment]
Exactly. Similarly for rushjs.io.

**Comment by psjishnu** [comment]
@sachinjoseph 
I will take a try

**Comment by octogonz** [comment]
Fixed in https://github.com/microsoft/rushjs.io-website/pull/64
