### ISSUE TITLE
Typo: "Yarn package" looks like "Yarnpackage"

### ISSUE THREAD

**Issue by sshongru** [microsoft/rushjs.io-website#68]
Steps to reproduce:
1. Go to https://rushjs.io/
2. Scroll down to the `No phantom dependencies!` section
3. Notice the word **Yarn**package

Actual Results:
<img width="901" alt="Screen Shot 2020-07-10 at 10 51 35 AM" src="https://user-images.githubusercontent.com/3753066/87183825-bb850d80-c29b-11ea-990e-f5c2149ee39d.png">

Expected Results:
<img width="908" alt="Screen Shot 2020-07-10 at 10 51 47 AM" src="https://user-images.githubusercontent.com/3753066/87183843-c0e25800-c29b-11ea-9bcd-65bb000e29f6.png">

Fix:

One character change needed at https://github.com/microsoft/rushjs.io-website/blob/eb03edf46cf9d3239d5ce2a9e8bfa18e5308df34/permalinks/home.html#L108

**Comment by octogonz** [comment]
@sshongru thanks for reporting this!
