### ISSUE TITLE
Documentation for different versions

### ISSUE THREAD

**Issue by marmaak** [microsoft/rushjs.io-website#83]
Hi, what I am going to raise here is not an issue but more something that I really would like to understand since it is a problem (at least from my point of view) that I saw it in many other open source projects (eg: Webpack, at least in the past).

Here the question: why the documentation is not clearly referencing which version of the tool it is about? Of course I do not expect to find the docs for every single patch (even minor) update, but I think that something like what Angular is doing (a kind of dropdown that allows you to decide which version of the documentation you would like to read) will be great and really helpful, I suppose.

Maybe someone can argue that "you should try to keep your dev tools always up-to-date", but honestly in some companies it might be hard to do this and having a documentation related only to the latest version published (I'm not sure if it is really like this also for rush) it might be misleading for people whom use this tool. Someone else might say that "it hard to keep multiple version of the documentation" but in such case my question will be: "Ok, it's legit, but why?"

I would like to say that I am not here to blame anyone, but mostly because I really want to understand if my point of view is just wrong or - if I'm somehow right - why it could be that hard to keep the documentation linked to each released version (at least major ones)

Thanks in advance to whoever will partecipate to the discussion and help me understand better this - I would say - generic topic

**Comment by octogonz** [comment]
It's a good suggestion. The main reason we don't do that is the Jekyll documentation template doesn't have this feature.  So probably some nontrivial work would be required to get it working.  (Webpack [has a version 4 website](https://v4.webpack.js.org/), but just that one version, and you'll find that their website search always returns pages from the Webpack 5 version. Whereas [docs.python.org](https://docs.python.org) has a much more complete solution.)  

Another factor is that for the past three years, Rush has been on version 5.x with almost no breaking changes.  Rush's design is relatively good about accommodating new features without breaking existing contracts.  Thus upgrading hasn't been a pain point for most users, as far as I know.

With Rush 6 we are expecting a number of breaking changes.  So maybe we'll have to confront the problem with that release.

**Comment by octogonz** [comment]
BTW if you have specific examples where the documentation was misleading because you were using an old version, please share them.  Specific problems are often easier to solve than general ones. :-)

**Comment by octogonz** [comment]
BTW I just looked at Angular's website.  They have a combo box, but when you switch to an older version, the combo box always shows that version as being "latest", and they have no banner warning people that the page is outdated.  I wonder if they simply fork the entire website every time they release a new version.  😁

This problem is probably quite easy if you design it from day 1, but maybe difficult to retrofit onto a CMS whose architecture didn't consider it.

**Comment by marmaak** [comment]
Thanks for the quick feedback!

> BTW if you have specific examples where the documentation was misleading because you were using an old version, please share them. Specific problems are often easier to solve than general ones. :-)

In my case it was about a flag (--to-except) that can be used along with the build command. It looks like that in my current version of Rush (5.36.2) it is not available but docs contain something about it:
- https://rushjs.io/pages/developer/selecting_subsets/
- https://rushjs.io/pages/commands/rush_build/
But as I said it's not a big problem, but more the trigger point for my doubt

> BTW I just looked at Angular's website. They have a combo box, but when you switch to an older version, the combo box always shows that version as being "latest", and they have no banner warning people that the page is outdated. I wonder if they simply fork the entire website every time they release a new version. 😁

Yeah, I am not sure what they do under the hood, but at least it is a starting point (like the one about Python). In Webpack they changed their approach only with the latest major release and I assume it's because of a lot of breaking changes.

> It's a good suggestion

I am not a maintainer of any open source project (even if I would like) but I think that rush docs are one of the most well written out there with plenty of examples, figures and good explanation about "opinionated" choices, so as I said I am not here to complain but only to support all your great work! If you would like to keep this as an improvement it will be great from my POV, otherwise I will continue to be grateful for such a good tool!

> With Rush 6 we are expecting a number of breaking changes

I really hope not that many 😆

**Comment by octogonz** [comment]
The Rush documentation website has been moved to a new Git repo.  I've opened a new issue https://github.com/microsoft/rushstack-websites/issues/86 which supersedes this one.
